service: kamal-app
image: kamal-app

servers:
  web:
    - ec2-35-173-224-154.compute-1.amazonaws.com

registry:
  server: 922126656512.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: development

builder:
  arch: amd64
  remote: true  # Build on the server instead of locally

ssh:
  user: ubuntu
  keys:
    - ~/.ssh/kamal-server-key.pem