# Production environment specific configuration
# This file is merged with config/deploy.yml

servers:
  web:
    - ec2-98-93-202-251.compute-1.amazonaws.com
    - ec2-3-236-235-204.compute-1.amazonaws.com

env:
  clear:
    RAILS_ENV: production
  secret:
    - SECRET_KEY_BASE
