service: kamal-app
image: kamal-app

servers:
  web:
  - ec2-3-239-7-145.compute-1.amazonaws.com
  - ec2-35-175-121-232.compute-1.amazonaws.com
  - ec2-3-237-15-3.compute-1.amazonaws.com

registry:
  server: 922126656512.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: development

builder:
  arch: amd64

ssh:
  user: ubuntu
  keys:
    - ~/.ssh/kamal-server-key.pem