# Staging environment specific configuration
# This file is merged with config/deploy.yml

servers:
  web:
    - ec2-98-93-178-197.compute-1.amazonaws.com

env:
  clear:
    RAILS_ENV: staging
    KAMAL_VERSION: <%= `git rev-parse --short HEAD`.strip %>
  secret:
    - SECRET_KEY_BASE
