# Staging environment specific configuration
# This file is merged with config/deploy.yml

servers:
  web:
    - ec2-34-226-234-69.compute-1.amazonaws.com

env:
  clear:
    RAILS_ENV: staging
  secret:
    - SECRET_KEY_BASE
