service: kamal-app
image: kamal-app

servers:
  web:
  - ec2-98-92-58-253.compute-1.amazonaws.com

registry:
  server: 922126656512.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: production
  secret:
    - SECRET_KEY_BASE

builder:
  arch: amd64

ssh:
  user: ubuntu
  keys:
    - ~/.ssh/kamal-server-key.pem

# Use default HTTP port 80
proxy:
  app_port: 3000