# Production environment specific configuration
# This file is merged with config/deploy.yml

servers:
  web:
    - ec2-98-80-96-138.compute-1.amazonaws.com
    - ec2-3-236-9-129.compute-1.amazonaws.com

env:
  clear:
    RAILS_ENV: production
  secret:
    - SECRET_KEY_BASE
