# Production environment specific configuration
# This file is merged with config/deploy.yml

servers:
  web:
    - ec2-98-92-58-253.compute-1.amazonaws.com

env:
  clear:
    RAILS_ENV: production
    KAMAL_VERSION: <%= `git rev-parse --short HEAD`.strip %>
  secret:
    - SECRET_KEY_BASE